services:
  professoroakbot:
    build: .
    container_name: professor_oak_bot
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ${DATA_FOLDER:-botdata}:/database

    env_file:
      - path: stack.env
        required: false
      - path: .env
        required: false


volumes:
  botdata:


